import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import registerServiceWorker from './registerServiceWorker';
import 'regenerator-runtime';
import Bundler from './bundler';
import 'bootstrap/dist/css/bootstrap.min.css';
const styleLink = document.createElement("link");
styleLink.rel = "stylesheet";
styleLink.href = "https://cdn.jsdelivr.net/npm/semantic-ui/dist/semantic.min.css";
document.head.appendChild(styleLink);
ReactDOM.render(<Bundler/>, document.getElementById('root'));
registerServiceWorker();
